#!/usr/bin/env bash
# Vendor documentation sources into src/vendor/ for mdBook.
#
# Modes:
#   --from-fixtures       Copy public-safe fixtures (default for public CI)
#   --from-fleet-config   Pull from private tzervas/fleet-config (+ optional paths)
#
# Env:
#   FLEET_CONFIG_PATH     Existing local checkout (preferred over clone)
#   FLEET_CONFIG_REPO     Default: tzervas/fleet-config
#   FLEET_CONFIG_REF      Default: dev
#   FLEET_CONFIG_TOKEN    Optional PAT for private clone (or GH_TOKEN / GITHUB_TOKEN)
#   CONFORMANCE_SPEC_PATH Optional path to CONFORMANCE-SPEC.md
#   OVERRIDES_PATH        Optional path to OVERRIDES.md if missing upstream
#
# Never commits src/vendor/ — that directory is gitignored.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="${ROOT}/src/vendor"
MODE=""

usage() {
  sed -n '2,20p' "$0" | sed 's/^# \?//'
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-fixtures) MODE=fixtures; shift ;;
    --from-fleet-config) MODE=fleet; shift ;;
    -h|--help) usage ;;
    *) echo "unknown arg: $1" >&2; usage ;;
  esac
done

if [[ -z "${MODE}" ]]; then
  if [[ -n "${FLEET_CONFIG_PATH:-}" || -n "${FLEET_CONFIG_TOKEN:-}" || -n "${GH_TOKEN:-}" ]]; then
    MODE=fleet
  else
    MODE=fixtures
  fi
fi

rm -rf "${VENDOR}"
mkdir -p "${VENDOR}/policies" "${VENDOR}/rulesets" "${VENDOR}/conformance"

# Copy only book-safe documentation surfaces into src/vendor.
# Do NOT vendor scripts/ (token helpers, fleet ops) into the mdBook tree —
# mdBook copies non-markdown files into the HTML output, and this repo is PUBLIC.
copy_book_safe() {
  local src_root="$1"
  if [[ -d "${src_root}/policies" ]]; then
    find "${src_root}/policies" -type f \( -name '*.md' -o -name '*.markdown' \) -print0 \
      | while IFS= read -r -d '' f; do
          rel="${f#"${src_root}/policies/"}"
          mkdir -p "${VENDOR}/policies/$(dirname "${rel}")"
          cp -a "${f}" "${VENDOR}/policies/${rel}"
        done
  fi
  if [[ -d "${src_root}/rulesets" ]]; then
    find "${src_root}/rulesets" -type f \( -name '*.md' -o -name '*.markdown' -o -name '*.json' \) -print0 \
      | while IFS= read -r -d '' f; do
          rel="${f#"${src_root}/rulesets/"}"
          mkdir -p "${VENDOR}/rulesets/$(dirname "${rel}")"
          cp -a "${f}" "${VENDOR}/rulesets/${rel}"
        done
  fi
}

copy_tree() {
  local src="$1" dest="$2"
  mkdir -p "$(dirname "${dest}")"
  if [[ -d "${src}" ]]; then
    mkdir -p "${dest}"
    # shellcheck disable=SC2174
    cp -a "${src}/." "${dest}/"
  elif [[ -f "${src}" ]]; then
    mkdir -p "$(dirname "${dest}")"
    cp -a "${src}" "${dest}"
  else
    return 1
  fi
}

write_pin() {
  local mode="$1" commit="$2" extra="${3:-}"
  cat > "${VENDOR}/SOURCE-PIN.md" <<EOF
# Build source pin

| Field | Value |
|---|---|
| **Mode** | \`${mode}\` |
| **fleet-config commit** | \`${commit}\` |
| **Built (UTC)** | $(date -u +%Y-%m-%dT%H:%M:%SZ) |
| **docsite commit** | \`$(git -C "${ROOT}" rev-parse HEAD 2>/dev/null || echo unknown)\` |

${extra}

This page is generated by \`scripts/vendor-sources.sh\`. It is the authoritative
answer to "which revision of the rules am I reading?"
EOF
}

vendor_from_fixtures() {
  echo "==> vendoring from fixtures (public-safe)"
  copy_book_safe "${ROOT}/fixtures/fleet-config"
  # Drop executable stubs from fixtures if any were copied as non-md (none expected).
  copy_tree "${ROOT}/fixtures/conformance" "${VENDOR}/conformance"
  write_pin "fixtures" "fixtures (not a git commit)" \
    "> **Not operative policy.** Full fleet-config text was not fetched. Local operators with private-read access should rebuild with \`--from-fleet-config\`."
}

resolve_fleet_src() {
  if [[ -n "${FLEET_CONFIG_PATH:-}" ]]; then
    if [[ ! -d "${FLEET_CONFIG_PATH}" ]]; then
      echo "FLEET_CONFIG_PATH is not a directory: ${FLEET_CONFIG_PATH}" >&2
      exit 1
    fi
    echo "${FLEET_CONFIG_PATH}"
    return
  fi

  local repo="${FLEET_CONFIG_REPO:-tzervas/fleet-config}"
  local ref="${FLEET_CONFIG_REF:-dev}"
  local tmp
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/fleet-config-vendor.XXXXXX")"
  # shellcheck disable=SC2064
  trap "rm -rf '${tmp}'" EXIT

  local token="${FLEET_CONFIG_TOKEN:-${GH_TOKEN:-${GITHUB_TOKEN:-}}}"
  local url
  if [[ -n "${token}" ]]; then
    url="https://x-access-token:${token}@github.com/${repo}.git"
  else
    url="https://github.com/${repo}.git"
  fi

  echo "==> cloning ${repo}@${ref} (private; requires access)" >&2
  if ! git clone --depth 1 --branch "${ref}" "${url}" "${tmp}/repo" 2>/tmp/fleet-clone.err; then
    # retry default branch
    if ! git clone --depth 1 "${url}" "${tmp}/repo" 2>>/tmp/fleet-clone.err; then
      echo "clone failed — falling back to fixtures. stderr:" >&2
      cat /tmp/fleet-clone.err >&2 || true
      echo "FALLBACK"
      return
    fi
  fi
  # Only the path goes to stdout (captured by caller).
  printf '%s\n' "${tmp}/repo"
}

vendor_from_fleet() {
  local src
  src="$(resolve_fleet_src)"
  if [[ "${src}" == "FALLBACK" || -z "${src}" ]]; then
    vendor_from_fixtures
    return
  fi

  echo "==> vendoring from ${src}"
  local commit
  commit="$(git -C "${src}" rev-parse HEAD 2>/dev/null || echo unknown)"

  if [[ -d "${src}/policies" || -d "${src}/rulesets" ]]; then
    copy_book_safe "${src}"
  else
    echo "warn: no policies/rulesets in source; using fixtures" >&2
    copy_book_safe "${ROOT}/fixtures/fleet-config"
  fi

  # Intentionally NOT vendoring fleet-config/scripts into src/vendor (public HTML risk).

  # OVERRIDES may not yet live in fleet-config — allow explicit path, else fixture.
  if [[ ! -f "${VENDOR}/rulesets/OVERRIDES.md" ]]; then
    if [[ -n "${OVERRIDES_PATH:-}" && -f "${OVERRIDES_PATH}" ]]; then
      cp -a "${OVERRIDES_PATH}" "${VENDOR}/rulesets/OVERRIDES.md"
      echo "    + OVERRIDES.md from OVERRIDES_PATH"
    else
      cp -a "${ROOT}/fixtures/fleet-config/rulesets/OVERRIDES.md" "${VENDOR}/rulesets/OVERRIDES.md"
      echo "    + OVERRIDES.md from fixtures (missing upstream)"
    fi
  fi

  # Conformance spec: fleet-config path, CONFORMANCE_SPEC_PATH, or fixtures.
  local conf=""
  if [[ -f "${src}/docs/CONFORMANCE-SPEC.md" ]]; then
    conf="${src}/docs/CONFORMANCE-SPEC.md"
  elif [[ -f "${src}/policies/CONFORMANCE-SPEC.md" ]]; then
    conf="${src}/policies/CONFORMANCE-SPEC.md"
  elif [[ -n "${CONFORMANCE_SPEC_PATH:-}" && -f "${CONFORMANCE_SPEC_PATH}" ]]; then
    conf="${CONFORMANCE_SPEC_PATH}"
  fi
  if [[ -n "${conf}" ]]; then
    cp -a "${conf}" "${VENDOR}/conformance/CONFORMANCE-SPEC.md"
    echo "    + CONFORMANCE-SPEC.md from ${conf}"
  else
    copy_tree "${ROOT}/fixtures/conformance" "${VENDOR}/conformance"
    echo "    + CONFORMANCE-SPEC.md from fixtures (not found in source)"
  fi

  write_pin "fleet-config" "${commit}" \
    "Repository: \`${FLEET_CONFIG_REPO:-tzervas/fleet-config}\`  "$'\n'"Ref: \`${FLEET_CONFIG_REF:-dev}\`"
}

case "${MODE}" in
  fixtures) vendor_from_fixtures ;;
  fleet) vendor_from_fleet ;;
  *) echo "bad mode: ${MODE}" >&2; exit 1 ;;
esac

# Ensure SUMMARY-required paths exist
for req in \
  SOURCE-PIN.md \
  policies/BRANCH-AND-RELEASE-CONTRACT.md \
  policies/TESTING-POLICY.md \
  rulesets/README.md \
  rulesets/OVERRIDES.md \
  conformance/CONFORMANCE-SPEC.md
do
  if [[ ! -e "${VENDOR}/${req}" ]]; then
    echo "error: missing required vendored path: ${req}" >&2
    exit 1
  fi
done

# JSON rulesets required for examples
for req in trunk-default-gated.json trunk-integration-guarded.json; do
  if [[ ! -f "${VENDOR}/rulesets/${req}" ]]; then
    echo "error: missing ruleset JSON: ${req}" >&2
    exit 1
  fi
done

echo "==> vendor complete → ${VENDOR}"
ls -la "${VENDOR}" "${VENDOR}/policies" "${VENDOR}/rulesets" "${VENDOR}/conformance"
